// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaspWorkFlowCore;

namespace WaspWorkFlowCore.Migrations
{
    [DbContext(typeof(WFContext))]
    [Migration("20191108031713_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WaspWorkFlowCore.Models.Examples.SpringTourApply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Area");

                    b.Property<string>("CounsellorOptions");

                    b.Property<Guid>("CreateUserId");

                    b.Property<string>("CreateUserName");

                    b.Property<string>("HeadTeacherOptions");

                    b.Property<string>("Name");

                    b.Property<int>("ParticipantNum");

                    b.Property<long>("Price");

                    b.Property<long>("StartTime");

                    b.Property<int>("TotalDay");

                    b.HasKey("Id");

                    b.ToTable("SpringTourApply");
                });

            modelBuilder.Entity("WaspWorkFlowCore.Models.WFInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BId");

                    b.Property<string>("BType");

                    b.Property<string>("Desc");

                    b.Property<Guid>("WFId");

                    b.HasKey("Id");

                    b.ToTable("WFInstance");
                });

            modelBuilder.Entity("WaspWorkFlowCore.Models.WFLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("LineId");

                    b.Property<string>("LineJson");

                    b.Property<Guid>("WFId");

                    b.HasKey("Id");

                    b.ToTable("WFLine");
                });

            modelBuilder.Entity("WaspWorkFlowCore.Models.WFNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NodeJson");

                    b.Property<Guid>("WFId");

                    b.HasKey("Id");

                    b.ToTable("WFNode");
                });

            modelBuilder.Entity("WaspWorkFlowCore.Models.WFNodeInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionLogs");

                    b.Property<Guid>("BId");

                    b.Property<string>("BType");

                    b.Property<int>("State");

                    b.Property<Guid>("UserId");

                    b.Property<string>("UserName");

                    b.Property<Guid>("WFId");

                    b.Property<Guid>("WFInstanceId");

                    b.Property<Guid>("WFNodeId");

                    b.HasKey("Id");

                    b.ToTable("WFNodeInstance");
                });

            modelBuilder.Entity("WaspWorkFlowCore.Models.WFTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CreateTime");

                    b.Property<Guid>("CreateUserId");

                    b.Property<string>("CreateUserName");

                    b.Property<string>("Desc");

                    b.Property<bool>("IsDelete");

                    b.Property<string>("Name");

                    b.Property<long>("UpdateTime");

                    b.Property<Guid>("UpdateUserId");

                    b.Property<string>("UpdateUserName");

                    b.Property<string>("Version");

                    b.HasKey("Id");

                    b.ToTable("WFTemplate");
                });

            modelBuilder.Entity("WaspWorkFlowCore.Models.WFToolTip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TipDef");

                    b.Property<Guid>("TipId");

                    b.Property<Guid>("WFId");

                    b.HasKey("Id");

                    b.ToTable("WFToolTip");
                });
#pragma warning restore 612, 618
        }
    }
}
