// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkflowExample;

namespace WorkflowExample.Migrations
{
    [DbContext(typeof(ExampleContext))]
    partial class ExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WorkflowExample.Models.AssetPuchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BillId");

                    b.Property<double>("EstimatedAmount");

                    b.Property<int>("InventoryOnHand");

                    b.Property<string>("Name");

                    b.Property<int>("PurchaseQuantity");

                    b.Property<string>("Purpose");

                    b.Property<string>("Specifications");

                    b.HasKey("Id");

                    b.ToTable("AssetPuchase");
                });

            modelBuilder.Entity("WorkflowExample.Models.ITPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ApplicantId");

                    b.Property<string>("ApplicantName");

                    b.Property<string>("BillName");

                    b.Property<string>("CompanyName");

                    b.Property<int>("Count");

                    b.Property<long>("CreateTime");

                    b.Property<long>("DataOfSDP");

                    b.Property<long>("DataOfSFM");

                    b.Property<long>("DataOfSGM");

                    b.Property<long>("DataOfSVGM");

                    b.Property<string>("DepartmentId");

                    b.Property<string>("DepartmentName");

                    b.Property<double>("EstimatedAmount");

                    b.Property<int>("HadCount");

                    b.Property<Guid>("ProjectId");

                    b.Property<string>("ProjectName");

                    b.Property<string>("SignatureOfDP");

                    b.Property<string>("SignatureOfFM");

                    b.Property<string>("SignatureOfGM");

                    b.Property<string>("SignatureOfVGM");

                    b.HasKey("Id");

                    b.ToTable("ITPurchase");
                });
#pragma warning restore 612, 618
        }
    }
}
